# Generated by Django 2.2.5 on 2019-09-09 17:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 9, 17, 57, 14, 334973, tzinfo=utc), verbose_name='pub_date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='url',
            name='short_url',
            field=models.CharField(default=123456, max_length=6),
            preserve_default=False,
        ),
    ]
