# Generated by Django 2.2.9 on 2020-02-14 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='book',
            name='year_published',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
