# Generated by Django 2.2.9 on 2020-02-07 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_dos', '0002_auto_20200207_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date completed'),
        ),
    ]
