# Generated by Django 2.2.9 on 2020-02-06 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_diaryday_diaryentry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diaryentry',
            old_name='day',
            new_name='date',
        ),
    ]
