# Generated by Django 2.2.9 on 2020-02-08 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryday',
            name='training',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='diaryday',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='tracker.UserProfile'),
            preserve_default=False,
        ),
    ]
