# Generated by Django 2.2.9 on 2020-02-07 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('from_key', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myone_app.Key')),
                ('string', models.CharField(max_length=32)),
            ],
        ),
    ]
