# Generated by Django 2.2.9 on 2020-02-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Macros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meas_sys', models.BooleanField()),
                ('weight', models.IntegerField()),
                ('bfp', models.IntegerField()),
                ('act_lvl', models.FloatField()),
                ('goal', models.BooleanField()),
                ('lbm', models.IntegerField()),
                ('bmr', models.IntegerField()),
                ('protein', models.IntegerField()),
                ('train_kcal', models.IntegerField()),
                ('train_fat', models.IntegerField()),
                ('train_carb', models.IntegerField()),
                ('rest_kcal', models.IntegerField()),
                ('rest_fat', models.IntegerField()),
                ('rest_carb', models.IntegerField()),
            ],
        ),
    ]
