# Generated by Django 2.2.9 on 2020-03-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='macros',
            name='rdci',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='macros',
            name='tadci',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='macros',
            name='tdee',
            field=models.IntegerField(default=3000),
            preserve_default=False,
        ),
    ]
