# Generated by Django 2.2.9 on 2020-03-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_auto_20200315_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='macros',
            name='tdci',
            field=models.IntegerField(default=4000),
            preserve_default=False,
        ),
    ]
