# Generated by Django 3.0.3 on 2020-03-04 02:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorites',
            field=models.ManyToManyField(to='cc.ArtPiece'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='instagram',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='layout',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='patreon',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(default=1, upload_to=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='soundcloud',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='theme',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
