# Generated by Django 3.0.3 on 2020-03-04 03:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0002_auto_20200303_1945'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20200303_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email_address')),
                ('name', models.CharField(max_length=32)),
                ('location', models.CharField(max_length=64)),
                ('bio', models.CharField(max_length=3000)),
                ('mediums', models.CharField(max_length=200)),
                ('misc', models.CharField(max_length=1000)),
                ('theme', models.CharField(max_length=150)),
                ('layout', models.CharField(max_length=150)),
                ('instagram', models.CharField(max_length=150)),
                ('patreon', models.CharField(max_length=150)),
                ('soundcloud', models.CharField(max_length=150)),
                ('profile_pic', models.ImageField(upload_to=None)),
                ('favorites', models.ManyToManyField(to='cc.ArtPiece')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
