# Generated by Django 3.0.3 on 2020-03-05 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200303_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Medium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='layout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Layout'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mediums',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Medium'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Theme'),
        ),
    ]
