# Generated by Django 3.0.3 on 2020-03-05 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200304_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='layout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Layout'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mediums',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Medium'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Theme'),
        ),
    ]
