# Generated by Django 3.0.3 on 2020-03-05 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0003_auto_20200303_1945'),
        ('users', '0007_auto_20200304_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(blank=True, to='cc.ArtPiece'),
        ),
    ]
