# Generated by Django 3.0.3 on 2020-03-06 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200304_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='mediums',
        ),
        migrations.AddField(
            model_name='profile',
            name='mediums',
            field=models.ManyToManyField(blank=True, to='users.Medium'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='text',
            field=models.CharField(default='Dark', max_length=150),
        ),
    ]
