# Generated by Django 3.0.3 on 2020-03-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200305_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layout',
            name='text',
            field=models.CharField(default='Type 1', max_length=150),
        ),
    ]
