# Generated by Django 3.0.3 on 2020-03-08 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200308_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='layout',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='users.Layout'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='theme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='users.Theme'),
        ),
    ]
