# Generated by Django 3.0.3 on 2020-03-08 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20200308_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layout',
            name='text',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='layout',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='users.Layout'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='theme',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='users.Theme'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='text',
            field=models.CharField(max_length=150),
        ),
    ]
