# Generated by Django 3.0.3 on 2020-03-08 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20200308_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='layout',
            field=models.ForeignKey(default='Type 1', null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Layout'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='theme',
            field=models.ForeignKey(default='Dark', null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Theme'),
        ),
    ]
