# Generated by Django 3.0.3 on 2020-03-08 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20200308_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layout',
            name='text',
            field=models.CharField(default='Type 1', max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='layout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Layout'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Theme'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='text',
            field=models.CharField(default='Dark', max_length=150),
        ),
    ]
