# Generated by Django 3.0.3 on 2020-03-11 02:11

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20200309_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.Profile.user_directory_path),
        ),
    ]
