# Generated by Django 3.0.3 on 2020-03-11 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20200310_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='users/{0}/{1}.format(user.id, filename)'),
        ),
    ]
