# Generated by Django 2.2.9 on 2020-03-28 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LongUrlTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.CharField(max_length=1000000)),
            ],
        ),
        migrations.CreateModel(
            name='ShortUrlTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortened_url', models.CharField(max_length=1000000)),
                ('original_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='url_shortener.LongUrlTask')),
            ],
        ),
    ]
