# Generated by Django 2.2.9 on 2020-03-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.CharField(max_length=1000000)),
                ('shortened_url', models.CharField(max_length=1000000)),
            ],
        ),
        migrations.RemoveField(
            model_name='shorturltask',
            name='original_url',
        ),
        migrations.DeleteModel(
            name='LongUrlTask',
        ),
        migrations.DeleteModel(
            name='ShortUrlTask',
        ),
    ]
