# Generated by Django 2.2.9 on 2020-02-22 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myspace_pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postgroup',
            name='title',
        ),
    ]
