# Generated by Django 2.2.9 on 2020-03-06 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myspace_pages', '0002_remove_postgroup_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePicChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
            ],
        ),
    ]
