# Generated by Django 2.2.9 on 2020-03-14 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myspace_pages', '0007_auto_20200307_0300'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileMusicChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music', models.FileField(blank=True, null=True, upload_to='music/')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_music',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='myspace_pages.ProfileMusicChoice'),
        ),
    ]
