# Generated by Django 2.2.9 on 2020-02-29 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('location', models.CharField(max_length=64)),
                ('bio', models.CharField(max_length=3000)),
                ('mediums', models.CharField(max_length=200)),
                ('misc', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ArtPiece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('pub_date', models.DateField()),
                ('medium', models.CharField(max_length=32)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cc.Artist')),
            ],
        ),
    ]
