# Generated by Django 3.0.3 on 2020-03-04 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artpiece',
            name='editors_choice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artpiece',
            name='watermark',
            field=models.BooleanField(default=True),
        ),
    ]
