# Generated by Django 3.0.3 on 2020-03-04 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0002_auto_20200303_1945'),
        ('users', '0003_auto_20200303_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artpiece',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
