# Generated by Django 3.0.3 on 2020-03-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0003_auto_20200303_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='artpiece',
            name='category',
            field=models.CharField(default=2, max_length=150),
            preserve_default=False,
        ),
    ]
