# Generated by Django 3.0.3 on 2020-03-15 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0008_artpiece_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artpiece',
            name='pub_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
