# Generated by Django 3.0.3 on 2020-03-15 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0009_auto_20200315_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artpiece',
            name='artist',
            field=models.CharField(max_length=24),
        ),
    ]
