# Generated by Django 3.0.3 on 2020-03-17 01:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0010_auto_20200315_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionpiece',
            name='pub_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
