# Generated by Django 2.2.9 on 2020-02-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20200213_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='general',
            field=models.BooleanField(default=False),
        ),
    ]
