# Generated by Django 2.2.9 on 2020-01-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_auto_20200124_2114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='todo_completed',
            new_name='todo_completed_bool',
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='todo_created',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='todo_created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
