# Generated by Django 2.2.9 on 2020-01-25 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_auto_20200124_2320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='todo_completed_bool',
            new_name='completed_bool',
        ),
        migrations.RenameField(
            model_name='todoitem',
            old_name='todo_created_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='todoitem',
            old_name='todo_text',
            new_name='text',
        ),
    ]
