# Generated by Django 2.2.9 on 2020-03-06 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20200304_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryday',
            name='training',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
