# Generated by Django 3.0.2 on 2020-03-11 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('position', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, choices=[('Goalkeeper', 'Goalkeeper'), ('Right-Fullback', 'Right-Fullback'), ('Left-Fullback', 'Left-Fullback'), ('Center-Back', 'Center-Back'), ('Sweeper', 'Sweeper'), ('Defending-Midfielder', 'Defending-Midfielder'), ('Right-Midfielder', 'Right-Midfielder'), ('Center-Midfielder', 'Center-Midfielder'), ('Striker', 'Striker'), ('Attacking-Midfielder', 'Attacking-Midfielder'), ('Left-Midfielder', 'Left-Midfielder')], max_length=30)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('number', models.CharField(blank=True, max_length=15)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('file', models.FileField(blank=True, max_length=300, upload_to='photos')),
                ('starter', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
