# Generated by Django 2.2.9 on 2020-02-19 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_auto_20200218_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='macros',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
