# Generated by Django 2.2.9 on 2020-02-01 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x0', models.IntegerField()),
                ('y0', models.IntegerField()),
                ('x1', models.IntegerField()),
                ('y1', models.IntegerField()),
            ],
        ),
    ]
