# Generated by Django 2.2.9 on 2020-03-10 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup_part2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='users_mother',
            new_name='user_mom',
        ),
        migrations.RenameField(
            model_name='userdetails',
            old_name='users_pet',
            new_name='user_pet',
        ),
    ]
