# Generated by Django 2.2.9 on 2020-02-11 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshort', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkstart',
            name='code',
            field=models.CharField(default='abc', max_length=9),
            preserve_default=False,
        ),
    ]
