# Generated by Django 2.2.9 on 2020-03-05 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryday',
            name='training',
            field=models.BooleanField(null=True),
        ),
    ]
